---
# Can be true, false, or http/https to enable just one of the protocols
:enabled: true

# Valid providers:
#   dns_nsupdate
#   dns_nsupdate_gss (for GSS-TSIG support)
#   dns_libvirt
#   dns_dnscmd
:use_provider: dns_libvirt
# use this setting if you want to override default TTL setting (86400)
#:dns_ttl: 86400

